# Generated by Django 4.2.13 on 2025-01-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='prompt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
