# Generated by Django 4.2.13 on 2025-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_backgroundimage_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
