# Generated by Django 4.2.13 on 2025-01-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_alter_backgroundimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
