# Generated by Django 4.2.13 on 2025-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0004_alter_backgroundimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
