# Generated by Django 4.2.13 on 2025-01-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_options_alter_campaign_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
    ]
