# Generated by Django 4.2.13 on 2025-01-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_options_alter_campaign_description'),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasstate',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_state', to='campaign.campaign'),
        ),
    ]
