# Generated by Django 4.2.13 on 2025-01-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_alter_canvasstate_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasstate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='canvasstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
