# Generated by Django 4.2.13 on 2025-03-05 20:49

import canvas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_alter_canvasstate_options_canvasstate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasstate',
            name='data',
            field=models.JSONField(default=canvas.models.get_default_canvas_state),
        ),
    ]
